import Head from "next/head";
import Header from "../components/Header";
import Tracks from "../components/Tracks";
import { useState } from "react";

export default function Home() {
  const [selected, setSelected] = useState(null);
  const [playing, setPlaying] = useState(false);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header playing={playing} setPlaying={setPlaying} selected={selected} />
      <Tracks
        playing={playing}
        setPlaying={setPlaying}
        selected={selected}
        setSelected={setSelected}
      />
    </div>
  );
}
